use anyhow::Result;

pub fn generate_init_script() -> String {
    format!(
        r#"# envhist shell integration
# This file is automatically generated by envhist init

_envhist_export() {{
    # Parse arguments - handle both "export KEY=value" and "export KEY value"
    local key
    local value
    
    if [[ "$1" == *"="* ]]; then
        # Format: export KEY=value
        key="${{1%%=*}}"
        value="${{1#*=}}"
        shift
    else
        # Format: export KEY value
        key="$1"
        value="$2"
        shift 2
    fi
    
    # Send to daemon
    envhist send-set $$ "$key" "$value" 2>/dev/null || true
    
    # Actually do the export
    if [ $# -eq 0 ]; then
        builtin export "$key"="$value"
    else
        builtin export "$key"="$value" "$@"
    fi
}}

# Wrap export command
alias export='_envhist_export'

_envhist_unset() {{
    local key="$1"
    
    # Send to daemon
    envhist send-unset $$ "$key" 2>/dev/null || true
    
    # Actually do the unset
    builtin unset "$key"
}}

# Wrap unset command  
alias unset='_envhist_unset'

_envhist_precmd() {{
    # Capture env state before prompt (throttled to avoid overhead)
    # Only capture every 10th prompt to reduce overhead
    if [ -z "$_envhist_counter" ]; then
        _envhist_counter=0
    fi
    _envhist_counter=$((_envhist_counter + 1))
    
    if [ $((_envhist_counter % 10)) -eq 0 ]; then
        envhist send-capture $$ 2>/dev/null || true
    fi
}}

# Add precmd hook (zsh)
if [ -n "$ZSH_VERSION" ]; then
    autoload -Uz add-zsh-hook
    add-zsh-hook precmd _envhist_precmd
fi

# Cleanup on exit
_envhist_cleanup() {{
    # Session cleanup is handled by daemon detecting process termination
    :
}}

trap _envhist_cleanup EXIT
"#
    )
}

pub fn install_hooks(zshrc_path: &std::path::Path) -> Result<()> {
    use std::fs::OpenOptions;
    use std::io::Write;

    let init_script = generate_init_script();
    let marker = "# envhist shell integration";

    // Check if already installed
    let content = std::fs::read_to_string(zshrc_path).unwrap_or_else(|_| String::new());

    if content.contains(marker) {
        return Ok(()); // Already installed
    }

    // Append to .zshrc
    let mut file = OpenOptions::new()
        .create(true)
        .append(true)
        .open(zshrc_path)?;

    writeln!(file, "\n{}", init_script)?;

    Ok(())
}
